config/routes.rb
Rails.application.routes.draw do
  root 'reciprocals#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'help' => 'pages#help', as: 'help'

  resources :reciprocals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reciprocal.rb
class Reciprocal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about # вызывает шаблон views/pages/about.html.erb
    @heading = 'Сторінка про нас!' # переменная вывода информации
  end

  def help

  end
end

app/controllers/reciprocals_controller.rb
require_relative 'F:\RubyOnRailsProjects\Stochastic_Course\app\distribution\Modules.rb'
include NeymanModule # модуль методу Неймана
include MetropolisModule # модуль методу Метрополіса
include ReverseModule # модуль методу зворотної функції
include DiagramsInfoModule # модуль методу Метрополіса
include VisualizationModule # модуль методів для гістограм
include ResultModule # модуль результатів

class ReciprocalsController < ApplicationController
  before_action :set_reciprocal, only: %i[ show edit update destroy ]

  # GET /reciprocals or /reciprocals.json
  def index
    @reciprocals = Reciprocal.all
    length = Reciprocal.all.length

    if length == 0
      alf = 1.0
      bet = 4.0
      val_n = 200.0
      n_g = 20.0
    else
      @reciprocal = Reciprocal.find(length)
      alf = @reciprocal.x.to_f
      bet = @reciprocal.y.to_f
      val_n = @reciprocal.val_n.to_f
      n_g = @reciprocal.n_g.to_f
    end

    helper_methods = helper_result(alf, bet, val_n, n_g).dig(:methods)
    helper_frequencies = helper_result(alf, bet, val_n, n_g).dig(:frequencies)

    @pdf = method_pdf(alf, bet, val_n)
    @p_k = approx_distribution_visual(alf, bet, n_g)
    @series_one_neyman = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_one_neyman))
    @series_two_neyman = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_two_neyman))
    @series_one_metropolis = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_one_metropolis))
    @series_two_metropolis = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_two_metropolis))
    @series_one_reverse = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_one_reverse))
    @series_two_reverse = series_visual(alf, bet, n_g, helper_frequencies.dig(:frequency_two_reverse))

    @average = result_average(alf, bet)
    @mode = alf
    @dispersion = result_dispersion(alf, bet)

    @average_series_one_neyman = result_average_series(helper_methods.dig(:neyman_for_first))
    @average_series_two_neyman = result_average_series(helper_methods.dig(:neyman_for_second))

    @average_series_one_metropolis = result_average_series(helper_methods.dig(:metropolis_for_first))
    @average_series_two_metropolis = result_average_series(helper_methods.dig(:metropolis_for_second))

    @average_series_one_reverse = result_average_series(helper_methods.dig(:reverse_for_first))
    @average_series_two_reverse = result_average_series(helper_methods.dig(:reverse_for_second))

    @mode_series_one_neyman = result_mode_series(helper_methods.dig(:neyman_for_first))
    @mode_series_two_neyman = result_mode_series(helper_methods.dig(:neyman_for_second))

    @mode_series_one_metropolis = result_mode_series(helper_methods.dig(:metropolis_for_first))
    @mode_series_two_metropolis = result_mode_series(helper_methods.dig(:metropolis_for_second))

    @mode_series_one_reverse = result_mode_series(helper_methods.dig(:reverse_for_first))
    @mode_series_two_reverse = result_mode_series(helper_methods.dig(:reverse_for_second))

    @dispersion_series_one_neyman = result_dispersion_series(helper_methods.dig(:neyman_for_first))
    @dispersion_series_two_neyman = result_dispersion_series(helper_methods.dig(:neyman_for_second))

    @dispersion_series_one_met = result_dispersion_series(helper_methods.dig(:metropolis_for_first))
    @dispersion_series_two_met = result_dispersion_series(helper_methods.dig(:metropolis_for_second))

    @dispersion_series_one_reverse = result_dispersion_series(helper_methods.dig(:reverse_for_first))
    @dispersion_series_two_reverse = result_dispersion_series(helper_methods.dig(:reverse_for_second))
    #@reciprocals = Reciprocal.all
  end

  # GET /reciprocals/1 or /reciprocals/1.json
  def show
  end

  # GET /reciprocals/new
  def new
    @reciprocal = Reciprocal.new
  end

  # GET /reciprocals/1/edit
  def edit
  end

  # POST /reciprocals or /reciprocals.json
  def create
    @reciprocal = Reciprocal.new(reciprocal_params)

    respond_to do |format|
      if @reciprocal.save
        format.html { redirect_to home_url(@reciprocal)}
        format.json { render :show, status: :created, location: @reciprocal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reciprocal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reciprocals/1 or /reciprocals/1.json
  def update
    respond_to do |format|
      if @reciprocal.update(reciprocal_params)
        format.html { redirect_to reciprocals_url(@reciprocal)}
        format.json { render :show, status: :ok, location: @reciprocal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reciprocal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reciprocals/1 or /reciprocals/1.json
  def destroy
    @reciprocal.destroy

    respond_to do |format|
      format.html { redirect_to reciprocals_url}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reciprocal
    @reciprocal = Reciprocal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reciprocal_params
    params.require(:reciprocal).permit(:x, :y, :val_n, :n_g)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reciprocals_helper.rb
module ReciprocalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obraztsov_CourseWork</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
      <title>Reciprocal</title>

      <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
    </svg>
    <span class="fs-4 font-weight-bold">Взаємний розподіл</span>
  </a>

  <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
    <!-- span - ссылки -->
    <!-- home_path - home выставляется в routes -->

    <span class="me-3 py-2 text-dark text-decoration-none"><%= link_to "Головна сторінка", home_path, :class => "btn btn-warning" %></span>
    <span class="me-3 py-2 text-dark text-decoration-none"><%= link_to "Про нас", about_path, :class => "btn btn-primary" %></span>
    <span class="me-3 py-2 text-dark text-decoration-none"><%= link_to "Потрібна допомога?", help_path, :class => "btn btn-light" %></span>
  </nav>
  <!-- new_post_path из результата rails routes-->

</div>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div style="text-align: center; font-family: 'Times New Roman',serif; font-size: 20px">
    <h1><%= @heading %></h1>

    <hr>

    <h5>Виконавцем наведеної роботи є студент групи КС43 - Образцов Дмитро.<br>Гарним описом всього процесу розробки та
      підготовки є наступна цитата: «Сенс життя не в тому, щоб чекати, коли закінчиться гроза, а в тому, щоб вчитися
      танцювати під дощем!»</h5><br><br>

    <dfn>P.s. Не знав де ще вибачитись за запізнення, тому просто вибачусь тут ще раз! Вибачте будь ласка!</dfn>

    <hr>


  </div>
</div>

app/views/reciprocals/_form.html.erb
<%= form_with(model: reciprocal) do |form| %>
  <% if reciprocal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reciprocal.errors.count, "error") %> prohibited this reciprocal from being saved:</h2>

      <ul>
        <% reciprocal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :y, style: "display: block" %>
    <%= form.text_field :y %>
  </div>

  <div>
    <%= form.label :val_n, style: "display: block" %>
    <%= form.text_field :val_n %>
  </div>

  <div>
    <%= form.label :n_g, style: "display: block" %>
    <%= form.text_field :n_g %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reciprocals/_reciprocal.html.erb
<div id="<%= dom_id reciprocal %>">
  <p>
    <strong>X:</strong>
    <%= reciprocal.x %>
  </p>

  <p>
    <strong>Y:</strong>
    <%= reciprocal.y %>
  </p>

  <p>
    <strong>Val n:</strong>
    <%= reciprocal.val_n %>
  </p>

  <p>
    <strong>N g:</strong>
    <%= reciprocal.n_g %>
  </p>

</div>

app/views/reciprocals/edit.html.erb
<h1>Editing reciprocal</h1>

<%= render "form", reciprocal: @reciprocal %>

<br>

<div>
  <%= link_to "Show this reciprocal", @reciprocal %> |
  <%= link_to "Back to reciprocals", reciprocals_path %>
</div>

app/views/reciprocals/index.html.erb
<link rel="stylesheet" href="application.css">
<p style="color: green"><%= notice %></p>

<div style="font-family: 'Times New Roman',serif; font-size: 20px">
  <h1>Вхідні
    дані <%= image_tag 'ruby.jpg', width: 50, height: 50, style: "vertical-align:middle; -aw-left-pos:0pt; -aw-rel-hpos:column; -aw-rel-vpos:paragraph; -aw-top-pos:0pt; -aw-wrap-type:inline" %>
  </h1>

  <hr>

  <div style="text-align: center;">
    <%= form_for :reciprocal, url: reciprocals_path do |form| %>
      <div class="alert alert-info">
        Початок проміжку:
        <%= form.number_field :x, in: 0.0..1000.0, step: 1, :class => "form_control form-control-md", :id => "x"%>
        Завершення проміжку:
        <%= form.number_field :y, in: 0.0..1000.0, step: 1, :class => "form_control form-control-md", :id => "y"%><br><br>
        Кількість точок:
        <%= form.number_field :val_n, in: 5.0..10000000.0, step: 1, :class => "form_control form-control-md" %>
        Кількість інтервалів розбиття:
        <%= form.number_field :n_g, in: 5.0..1000.0, step: 1, :class => "form_control form-control-md" %><br><br>

        <%= form.submit "Зберегти", :class => "btn btn-success" %>
      </div>
    <% end %>
  </div>

  <hr>

  <h1>Функція щільності ймовірності
    розподілу <%= image_tag 'ruby.jpg', width: 50, height: 50, style: "vertical-align:middle; -aw-left-pos:0pt; -aw-rel-hpos:column; -aw-rel-vpos:paragraph; -aw-top-pos:0pt; -aw-wrap-type:inline" %></h1>

  <hr>

  <div class="alert alert-primary">
    <%= line_chart [
                     {
                       name: "ФШІ", type: 'line', data: @pdf
                     }
                   ],
                   title: "Функція щільності ймовірності",
                   colors: ['brown'],
                   xtitle: "x",
                   ytitle: "P(x)",
                   download: { background: "#ffffff" }
    %>
  </div>

  <hr>

  <h1>Статистична перевірка випадкових
    величин <%= image_tag 'ruby.jpg', width: 50, height: 50, style: "vertical-align:middle; -aw-left-pos:0pt; -aw-rel-hpos:column; -aw-rel-vpos:paragraph; -aw-top-pos:0pt; -aw-wrap-type:inline" %></h1>

  <hr>

  <h4 style="text-align: center">Використання методу Неймана</h4>

  <hr>
  <div class="alert alert-success">
    <%= column_chart [
                       {
                         name: "Апроксимація взаємного розподілу", type: 'column', data: @p_k
                       },
                       {
                         name: "Перша серія моделювання", type: 'column', data: @series_one_neyman
                       },
                       {
                         name: "Друга серія моделювання", type: 'column', data: @series_two_neyman
                       }
                     ],
                     title: "Статистична перевірка випадкових величин (Метод Неймана)",
                     colors: ['green', 'blue', 'purple'],
                     xtitle: "x",
                     ytitle: "p(x)",
                     download: { background: "#ffffff" }
    %>
  </div>

  <hr>

  <h4 style="text-align: center">Використання методу Метрополісу</h4>

  <hr>
  <div class="alert alert-success">
    <%= column_chart [
                       {
                         name: "Апроксимація взаємного розподілу", type: 'column', data: @p_k
                       },
                       {
                         name: "Перша серія моделювання", type: 'column', data: @series_one_metropolis
                       },
                       {
                         name: "Друга серія моделювання", type: 'column', data: @series_two_metropolis
                       }
                     ],
                     title: "Статистична перевірка випадкових величин (Метод Метрополісу)",
                     colors: ['green', 'blue', 'purple'],
                     xtitle: "x",
                     ytitle: "p(x)",
                     download: { background: "#ffffff" }
    %>
  </div>

  <hr>

  <h4 style="text-align: center">Використання методу зворотної функції</h4>

  <hr>
  <div class="alert alert-success">
    <%= column_chart [
                       {
                         name: "Апроксимація взаємного розподілу", type: 'column', data: @p_k
                       },
                       {
                         name: "Перша серія моделювання", type: 'column', data: @series_one_reverse
                       },
                       {
                         name: "Друга серія моделювання", type: 'column', data: @series_two_reverse
                       }
                     ],
                     title: "Статистична перевірка випадкових величин (Метод зворотної функції)",
                     colors: ['green', 'blue', 'purple'],
                     xtitle: "x",
                     ytitle: "p(x)",
                     download: { background: "#ffffff" }
    %>
  </div>

  <hr>

  <h1>Інтегральні
    характеристики <%= image_tag 'ruby.jpg', width: 50, height: 50, style: "vertical-align:middle; -aw-left-pos:0pt; -aw-rel-hpos:column; -aw-rel-vpos:paragraph; -aw-top-pos:0pt; -aw-wrap-type:inline" %></h1>

  <hr>
  <div style="background: #DDDDF5">
    <div style="text-align: center;">
      <table border="1" cellpadding="6" cellspacing="0" align="center">
        <tr>
          <td>&nbsp;</td>
          <td><b>Теоретичні значення</b></td>
          <td colspan="2"><b>Метод Неймана</b></td>
          <td colspan="2"><b>Метод Метрополісу</b></td>
          <td colspan="2"><b>Метод зворотної функції</b></td>
        </tr>
        <tr>
          <td><b>Інтегральні характеристики</b></td>
          <td style="background: #008000"></td>
          <td style="background: #0000FF"></td>
          <td style="background: #800080"></td>
          <td style="background: #0000FF"></td>
          <td style="background: #800080"></td>
          <td style="background: #0000FF"></td>
          <td style="background: #800080"></td>
        </tr>
        <tr>
          <td><b>Математичне очікування</b></td>
          <td><%= @average.round(5) %></td>
          <td><%= @average_series_one_neyman.round(5) %></td>
          <td><%= @average_series_two_neyman.round(5) %></td>
          <td><%= @average_series_one_metropolis.round(5) %></td>
          <td><%= @average_series_two_metropolis.round(5) %></td>
          <td><%= @average_series_one_reverse.round(5) %></td>
          <td><%= @average_series_two_reverse.round(5) %></td>
        </tr>
        <tr>
          <td><b>Дисперсія</b></td>
          <td><%= @dispersion.round(5) %></td>
          <td><%= @dispersion_series_one_neyman.round(5) %></td>
          <td><%= @dispersion_series_two_neyman.round(5) %></td>
          <td><%= @dispersion_series_one_met.round(5) %></td>
          <td><%= @dispersion_series_two_met.round(5) %></td>
          <td><%= @dispersion_series_one_reverse.round(5) %></td>
          <td><%= @dispersion_series_two_reverse.round(5) %></td>
        </tr>
        <tr>
          <td><b>Мода</b></td>
          <td><%= @mode.round(5) %></td>
          <td><%= @mode_series_one_neyman.round(5) %></td>
          <td><%= @mode_series_two_neyman.round(5) %></td>
          <td><%= @mode_series_one_metropolis.round(5) %></td>
          <td><%= @mode_series_two_metropolis.round(5) %></td>
          <td><%= @mode_series_one_reverse.round(5) %></td>
          <td><%= @mode_series_two_reverse.round(5) %></td>
        </tr>
      </table>
    </div>
  </div>
  <hr>
</div>

<!--<div id="reciprocals">
  <%# @reciprocals.each do |reciprocal| %>
    <%#= render reciprocal %>
    <p>
      <%#= link_to "Show this reciprocal", reciprocal %>
    </p>
  <%# end %>
</div>-->


<%#= link_to "New reciprocal", new_reciprocal_path %>

<script>
    document.getElementById("x").addEventListener('change', function () {
        let x = document.getElementById("x");
        let y = document.getElementById("y")

        y.min = +x.value;
    });
</script>

app/views/reciprocals/new.html.erb
<h1>New reciprocal</h1>

<%= render "form", reciprocal: @reciprocal %>

<br>

<div>
  <%= link_to "Back to reciprocals", reciprocals_path %>
</div>

app/views/reciprocals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reciprocal %>

<div>
  <%= link_to "Edit this reciprocal", edit_reciprocal_path(@reciprocal) %> |
  <%= link_to "Back to reciprocals", reciprocals_path %>

  <%= button_to "Destroy this reciprocal", @reciprocal, method: :delete %>
</div>